src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/accept-invite-group/accept-invite-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/accept-invite-group/accept-invite-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/create-group/create-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/create-group/create-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/invite-code-group/invite-code-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/invite-code-group/invite-code-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/leave-group/leave-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/leave-group/leave-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/make-user-group/make-user-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/make-user-group/make-user-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/update-description-group/update-description-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/update-description-group/update-description-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/update-subject-group/update-subject-group.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/group/update-subject-group/update-subject-group.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/misc/block-unblock-user/block-unblock-user.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/misc/block-unblock-user/block-unblock-user.useCase.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/misc/is-on-whatsapp/is-on-whatsapp.dto.ts, src/modules/@shared/infra/services/whatsapp/bailyes/usecase/misc/is-on-whatsapp/is-on-whatsapp.useCase.ts
Essa PR tem o objetivo de implementar os métodos de grupos e misc do baileys.
- Métodos dos grupos (criar, atualizar, sair, atualizar descrição,  atualizar, titulo, config de usuários e convite por código);
- Métodos de MISC (verificar numero wpp, bloquear e desbloquear usuário);
=> Baileys methods group

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/index.ts, src/main/routes/instance.route.ts, src/main/server/app.ts, src/main/server/server.ts, src/modules/@shared/domain/exceptions/error-handler.ts, src/modules/@shared/infra/persistence/settings/connection.ts, src/modules/baileys/facade/baileys.facade.interface.ts, src/modules/baileys/facade/baileysFacade.ts, src/modules/baileys/repository/auth-state-repository.ts, src/modules/baileys/usecase/instance/init/init-instance.dto.ts, src/modules/baileys/usecase/instance/init/init-instance.usecase.ts, src/presentation/controllers/baileys-controllers/index.ts, test/e2e/base.2e2.spec.ts, test/e2e/init-baileys-instance.e2e-spec.ts
Este Pull Request tem como objetivo implementar a funcionalidade de criação da instância do Baileys, a fim de viabilizar a integração eficiente com o serviço do WhatsApp.
- criada a rota POST /instance
- criada a classe BaileysComposer
- alternada a forma que se inicializa a conexão com o banco de dados
- criado o método `handleYupError` para lidar com erros de validação
- criada a função `dbDisconnect` para desconectar do banco de dados
- refatorado a classe `BaileysControllerFacade`, alterei a forma de acessar as propriedades privadas
- alteração na nomenclatura de algumas interfaces
- remoção de arquivos não utilizados
=> feat: inicia instancia do bailyes 

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/accep-invite-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/accep-invite-group.validator.ts, test/e2e/baileys-group/accept-invite-group.e2e-spec.ts
Este Pull Request tem como objetivo implementar a funcionalidade de criação da rota de aceitar um código de um grupo, a fim de viabilizar a integração eficiente com o serviço do WhatsApp.
- criada a rota PATCH/api/whatsapp/group/1/accept-invite
=> feat: to add route and test accept invite group

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/instance.route.ts, src/modules/baileys/domain/baileys.entity.ts, src/modules/baileys/facade/baileys.facade.interface.ts, src/modules/baileys/usecase/instance/init/init-instance.usecase.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/instance/get-qr-code.controller.ts, src/presentation/controllers/baileys-controllers/instance/init-baileys.controller.ts, src/presentation/validators/get-qr-code.validator.ts, test/e2e/get-qr-instance.e2e-spec.ts
Adiciona a funcionalidade de busca por QR code para se conectar ao WhatsApp conforme especificado nos requisitos. Este pull request inclui a implementação da rota GET /instance/:id/qr para gerar o QR code necessário para a conexão.
- Adiciona rota GET /instance/:id/qr em src/main/server/app.ts para gerar o QR code.
- Implementa a lógica para gerar o QR code com base no ID da instância e no parâmetro belongsTo.
- Atualiza os testes unitários para garantir que a rota retorne um status 200 e inclua o QR code no corpo da resposta.
- Adiciona uma função de utilidade para aguardar a geração do QR code antes de verificar o resultado nos testes.
=> Implementa da funcionalidade de geração de QR code para conectar-se ao WhatsApp

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/instance.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/instance/logout-instance.controller.ts
implemented this feature to deal with the disconnection of the Baileys instance
=> implements the Logout feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/create-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/create-group.validator.ts
implemented this feature to handle group creation
=> Implements the create group feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/instance.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/instance/get-info-instance.controller.ts
Esse PR tem o objetivo de implementar a feature de busca de informações da instancia do Baileys
=> feat: implement get instance info

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/make-user-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/baileys/group/make-user-grop.validator.ts
implemented this feature to handle make user group
=> Implements the make user group feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/main/routes/index.ts, src/main/routes/instance.route.ts, src/main/routes/message.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/message/send-text-message.controller.ts, src/presentation/validators/baileys/message/send-text-message.validator.ts
Esse Pr tem o objetivo de implementar a feature de envio de mensagem de texto utilizando Baileys
=> feat: implement send text message feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/update-description-group.controller.ts, src/presentation/controllers/baileys-controllers/group/update-subject-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/baileys/group/update-description-group.validator.ts, src/presentation/validators/baileys/group/update-subject-group.validator.ts
implemented this feature to handle description and subjet group
=> Implements the update description and subjet group feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/message.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/message/send-url-media-file.controller.ts, src/presentation/validators/baileys/message/send-url-media-file.validator.ts
Esse PR tem o objetivo de implementar a feature de envio de media url
=> feat: implement send media url feature

src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/update-settings-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/baileys/group/update-settings-group.validator.ts
implemented this feature to handle update settings group
=> Implements the update settings group feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/message.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/message/send-media-file.controller.ts, src/presentation/validators/baileys/message/send-media-file.validator.ts
Esse PR tem o objetivo de implementar a feature de envio de media utilizando Baileys
=> feat: implement send media feature

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/group.route.ts, src/presentation/controllers/baileys-controllers/group/invite-code-group.controller.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/validators/baileys/group/invite-code-group.validator.ts
implemented this feature to handle invite code group
=> Implements the invite code group feature

src/main/routes/group.route.ts, src/main/routes/index.ts, src/main/routes/instance.route.ts, src/main/routes/message.route.ts, src/modules/baileys/usecase/instance/init/init-instance.dto.ts, src/modules/baileys/usecase/message/send-url-media-file/send-url-media-file.usecase.dto.ts
adjust nomenclature routes and params usecases
=> Adjust nomenclature routes and params usecases

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/misc.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/misc/block-unblock-user.controller.ts, src/presentation/validators/baileys/misc/block-unblock-user.validator.ts
Implement block and unblock user
=> Implement block and unblock user

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/misc.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/misc/block-unblock-user.controller.ts, src/presentation/controllers/baileys-controllers/misc/get-profile-picture.controller.ts, src/presentation/validators/baileys/misc/block-unblock-user.validator.ts, src/presentation/validators/baileys/misc/get-profile-picture.validator.ts
=> Implement get profile picture

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/misc.route.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/misc/get-status-user.controller.ts, src/presentation/validators/baileys/misc/get-status-user.validator.ts
Implement controller get status user
=> Implement controller get status user

src/presentation/validators/baileys/group/create-group.validator.ts, src/presentation/validators/baileys/group/leave-group.validator.ts, src/presentation/validators/baileys/misc/block-unblock-user.validator.ts, src/presentation/validators/baileys/misc/get-profile-picture.validator.ts, src/presentation/validators/baileys/misc/update-profile-picture.validator.ts
=> Adjust validators

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-requests.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/pr-comment.yml, .github/workflows/stale.yml
Esse PR adiciona novas configurações pertinentes ao github
=> chore: add configs .github

src/presentation/controllers/baileys-controllers/misc/get-profile-picture.controller.ts
=> Adjust params controller

src/main/routes/group.route.ts
=> adjust route group

src/main/routes/instance.route.ts, src/main/routes/message.route.ts, src/main/routes/misc.route.ts, src/main/server/app.ts, src/modules/baileys/domain/baileys.entity.ts, src/modules/baileys/factory/baileysFactory.ts, src/modules/baileys/repository/baileys-instance-repository-in-memory.ts, src/modules/baileys/usecase/instance/logout/logout-instance-usecase.ts, src/modules/baileys/usecase/instance/logout/logout-instance.usecase.dto.ts, src/modules/baileys/usecase/message/send-media-file/send-media-file.usecase.dto.ts, src/modules/baileys/usecase/message/send-media-file/send-media-file.usecase.ts, src/modules/baileys/usecase/misc/get-profile-picture/get-profile-picture.useCase.ts, src/presentation/controllers/baileys-controllers/group/accep-invite-group.controller.ts, src/presentation/controllers/baileys-controllers/group/invite-code-group.controller.ts, src/presentation/controllers/baileys-controllers/misc/get-profile-picture.controller.ts, src/presentation/validators/baileys/message/send-media-file.validator.ts, src/presentation/validators/baileys/message/send-url-media-file.validator.ts, src/presentation/validators/get-qr-code.validator.ts, src/presentation/validators/init-baileys.validator.ts
=> Adjust flow completed

envs/.env.exemple
=> chore: update env

src/modules/baileys/facade/baileys.facade.interface.ts, src/modules/baileys/facade/baileysFacade.ts
This PR fixes the import of the DTOs
=> fixes the import of the DTOs

generate-token.js, package-lock.json, package.json, src/@types/express/index.d.ts, src/main/middlewares/ensure-authenticate.middleware.ts, src/main/routes/index.ts, src/modules/@shared/infra/config.ts
Implement a JWT authentication system in the middleware to verify the presence and validity of a JWT in the request headers. If valid, user roles are extracted and attached to the request object.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> JWT Authentication Implementation

src/main/compose/baileys/bailyes.composer.ts, src/main/routes/message.route.ts, src/modules/baileys/facade/baileys.facade.interface.ts, src/modules/baileys/facade/baileysFacade.ts, src/modules/baileys/facade/dtos/index.ts, src/modules/baileys/factory/baileysFactory.ts, src/modules/baileys/usecase/message/find-all-contacts/find-all-contacts.dto.ts, src/modules/baileys/usecase/message/find-all-contacts/find-all-contacts.usecase.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/message/find-all-contacts.controller.ts, src/presentation/validators/baileys/message/find-all-contacts.validator.ts
=> Implements find contacts

src/main/compose/baileys/bailyes.composer.ts, src/modules/baileys/facade/baileys.facade.interface.ts, src/modules/baileys/factory/baileysFactory.ts, src/modules/baileys/helpers/queue-bindings.ts, src/modules/baileys/usecase/message/delete-message/delete-message.useCase.ts, src/modules/baileys/usecase/message/delete-message/delete-message.usecase.dto.ts, src/modules/baileys/usecase/message/update-message/update-message.useCase.ts, src/modules/baileys/usecase/message/update-message/update-message.usecase.dto.ts, src/presentation/controllers/baileys-controllers/index.ts, src/presentation/controllers/baileys-controllers/message/delete-text-message.controller.ts, src/presentation/controllers/baileys-controllers/message/update-text-message.controller.ts, src/presentation/validators/baileys/message/delete-text-message.validator.ts, src/presentation/validators/baileys/message/update-text-message.validator.ts
=> style: format code
